name: Supervisely release
run-name: Supervisely ${{ github.repository }} app release
on:
  release:
    types: [published]
    branches:
      - main
      - master
jobs:
  Supervisely-Release:
    uses: my-test-organisaion/workflows/.github/workflows/release.yml@master
    secrets:
      SUPERVISELY_API_TOKEN: "${{ secrets.SUPERVISELY_API_TOKEN }}"
      GH_ACCESS_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      SERVER_ADDRESS: "${{ vars.SUPERVISELY_SERVER_ADDRESS }}"
      SLUG: "${{ github.repository }}"
      RELEASE_VERSION: "${{ github.event.release.tag_name }}"
      RELEASE_TITLE: "${{ github.event.release.name }}"
      SUBAPP_PATHS: "__ROOT_APP__, subapp"
