name: Supervisely release
run-name: Supervisely ${{ github.repository }} app release
on:
  release:
    types: [published]
    branches:
      - main
      - master
jobs:
  Supervisely-Release:
    uses: my-test-organisaion/workflows/.github/workflows/release.yml@main
    with:
      SERVER_ADDRESS: ${{ vars.SUPERVISELY_SERVER_ADDRESS }}
      SUPERVISELY_API_TOKEN: ${{ secrets.SUPERVISELY_API_TOKEN }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      SLUG: "${{ github.repository }}"
      RELEASE_VERSION: "${{ github.event.release.tag_name }}"
      RELEASE_TITLE: "${{ github.event.release.name }}"
      SUBAPP_PATHS: ("__ROOT_APP__" "subapp")
